### ISSUE TITLE
Order object page displays Order Response

### ISSUE THREAD

**Issue by buu700** [tradestation/webapi-docs#14]
http://tradestation.github.io/webapi-docs/en/objects/order/ is currently displaying order-response.md instead of order.md.

**Comment by johnjelinek** [comment]
@buu700 good catch! I'll get that fixed up, unless you want to send a pull request :)

**Comment by buu700** [comment]
Cool, just went ahead and sent a pull request.

**Comment by johnjelinek** [comment]
@buu700 thanks, I'll review to make sure pages get updated to point to the new reference too.

**Comment by johnjelinek** [comment]
LGTM :shipit:

**Comment by johnjelinek** [comment]
@buu700 you may need to reset your cache to see the pages updated.

**Comment by buu700** [comment]
Cool, thanks; the new page is displaying correctly.
