### ISSUE TITLE
No clear directions on obtaining API key / secret

### ISSUE THREAD

**Issue by patslevin** [tradestation/webapi-docs#18]
It looks like TradeStation needs to issue an API key / secret in order to start using this API, but there is nothing in the documentation that I can find as to how to obtain them.

Maybe this should be explained in the Overview section?

**Comment by johnjelinek** [comment]
@zungaphobia Thanks for the request. Currently the process is:
1. send an e-mail to webapi@tradestation.com
2. go through the approval steps

We're also close to releasing a new website that will help walk through these steps as well. In addition though, I can add a blurb about these steps to the docs.

**Comment by johnjelinek** [comment]
You can learn more here: http://developer.tradestation.com/getting-started-with-tradestation-webapi/

**Comment by shlomoa** [comment]
sent an e-mail, no response, tried all sorts of funny stuff but I want to do it the right way.
My client OS is Linux and python as programming language
