### ISSUE TITLE
Undocumented attributes in stream/quote/changes/

### ISSUE THREAD

**Issue by emaber** [tradestation/webapi-docs#21]
When receiving data from the "stream/quote/changes/" endpoint there are a number of attributes that are not documented (example: BitFlags, TradeType, DailyDate, DailyTime, DailyDateTime, maybe more).

Is there an updated version of the docs that include these?

**Comment by johnjelinek** [comment]
@emaber: Thank you for reporting this. We will make the endpoint match what our documentation provides. I will leave this open until it has been completed.

**Comment by lancehunt** [comment]
We are moving to Open API (Swagger) docs and plan to address these gaps in the future.

You can find the new docs here: https://tradestation.github.io/api-docs/
the associated repo is: https://github.com/tradestation/api-docs

**Comment by lancehunt** [comment]
Closing older issues
